language: php
php:
  - '7.0'
  - '7.1'
  - hhvm
  - hhvm-nightly
  - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly
        - php: hhvm-nightly

before_script:
  - composer install && composer dump-autoload -o

script: ./vendor/bin/phpunit